- full_name: "Myra H Wyckoff" 
  other_names: 
    - "Myra H Wyckoff" 
    - "Wyckoff MH" 
    - "Myra Wyckoff" 
    - "Wyckoff M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Eric B Ortigoza" 
  other_names: 
    - "Eric B Ortigoza" 
    - "Ortigoza EB" 
    - "Eric Ortigoza" 
    - "Ortigoza E" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Vishal S Kapadia" 
  other_names: 
    - "Vishal S Kapadia" 
    - "Kapadia VS" 
    - "Vishal Kapadia" 
    - "Kapadia V" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Rachel L Leon" 
  other_names: 
    - "Rachel L Leon" 
    - "Leon RL" 
    - "Rachel Leon" 
    - "Leon R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Venkatakrishna Kakkilaya" 
  other_names: 
    - "Venkatakrishna Kakkilaya"
    - "Venkat Kakkilaya" 
    - "Kakkilaya V" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 