- full_name: "Lina F Chalak" 
  other_names: 
    - "Lina F Chalak" 
    - "Chalak LF" 
    - "Lina Chalak" 
    - "Chalak L" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Elie G Abu Jawdeh" 
  other_names: 
    - "Elie G Abu Jawdeh" 
    - "Abu Jawdeh EG" 
    - "Elie Abu Jawdeh" 
    - "Abu Jawdeh E" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Syed T Ahmed" 
  other_names: 
    - "Syed T Ahmed" 
    - "Ahmed ST" 
    - "Syed Ahmed" 
    - "Ahmed S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Noorjahan Ali" 
  other_names: 
    - "Noorjahan Ali" 
    - "Ali N" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Dimitrios Angelis" 
  other_names: 
    - "Dimitrios Angelis" 
    - "Angelis D" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Asya Asghar" 
  other_names: 
    - "Asya Asghar" 
    - "Asghar A" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Kikelomo L Babata" 
  other_names: 
    - "Kikelomo L Babata" 
    - "Babata KL" 
    - "Kikelomo Babata" 
    - "Babata K" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Nicole A Bailey" 
  other_names: 
    - "Nicole A Bailey" 
    - "Bailey NA" 
    - "Nicole Bailey" 
    - "Bailey N" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Jesse Banales" 
  other_names: 
    - "Jesse Banales" 
    - "Banales J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Arya Batta" 
  other_names: 
    - "Arya Batta" 
    - "Batta A" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Lorraine E Bautista" 
  other_names: 
    - "Lorraine E Bautista" 
    - "Bautista LE" 
    - "Lorraine Bautista" 
    - "Bautista L" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Timothy S Brannon" 
  other_names: 
    - "Timothy S Brannon" 
    - "Brannon TS" 
    - "Timothy Brannon" 
    - "Brannon T" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Mandy Brasher" 
  other_names: 
    - "Mandy Brasher" 
    - "Brasher M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Danielle A Callaway" 
  other_names: 
    - "Danielle A Callaway" 
    - "Callaway DA" 
    - "Danielle Callaway" 
    - "Callaway D" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Walter W Chen" 
  other_names: 
    - "Walter W Chen" 
    - "Chen WW" 
    - "Walter Chen" 
    - "Chen W" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Melody Chiu" 
  other_names: 
    - "Melody Chiu" 
    - "Chiu M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Riti KI Chokshi" 
  other_names: 
    - "Riti KI Chokshi" 
    - "Chokshi RKI" 
    - "Riti Chokshi" 
    - "Chokshi R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Mary Crume" 
  other_names: 
    - "Mary Crume" 
    - "Crume M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Riddhi K Desai" 
  other_names: 
    - "Riddhi K Desai" 
    - "Desai RK" 
    - "Riddhi Desai" 
    - "Desai R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Chadi Eltaha" 
  other_names: 
    - "Chadi Eltaha" 
    - "Eltaha C" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Becky J Ennis" 
  other_names: 
    - "Becky J Ennis" 
    - "Ennis BJ" 
    - "Becky Ennis" 
    - "Ennis B" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Shamaila A Gill" 
  other_names: 
    - "Shamaila A Gill" 
    - "Gill SA" 
    - "Shamaila Gill" 
    - "Gill S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Charles Herrin" 
  other_names: 
    - "Charles Herrin" 
    - "Herrin C" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Margaret K Hoge" 
  other_names: 
    - "Margaret K Hoge" 
    - "Hoge MK" 
    - "Margaret Hoge" 
    - "Hoge M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "June Hu" 
  other_names: 
    - "June Hu" 
    - "Hu J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "John Ibrahim" 
  other_names: 
    - "John Ibrahim" 
    - "Ibrahim J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Jawahar Jagarapu" 
  other_names: 
    - "Jawahar Jagarapu" 
    - "Jagarapu J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Mambarambath A Jaleel" 
  other_names: 
    - "Mambarambath A Jaleel" 
    - "Jaleel MA" 
    - "Mambarambath Jaleel" 
    - "Jaleel M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Imran N Mir" 
  other_names: 
    - "Imran N Mir" 
    - "Mir IN" 
    - "Imran Mir" 
    - "Mir I" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Raj Jayanthan" 
  other_names: 
    - "Raj Jayanthan" 
    - "Jayanthan R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Julie Mirpuri" 
  other_names: 
    - "Julie Mirpuri" 
    - "Mirpuri J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Manjula Mudduluru" 
  other_names: 
    - "Manjula Mudduluru" 
    - "Mudduluru M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Sujir P Nayak" 
  other_names: 
    - "Sujir P Nayak" 
    - "Nayak SP" 
    - "Sujir Nayak" 
    - "Nayak S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Tetyana H Nesterenko" 
  other_names: 
    - "Tetyana H Nesterenko" 
    - "Nesterenko TH" 
    - "Tetyana Nesterenko" 
    - "Nesterenko T" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Rajesh Pandey" 
  other_names: 
    - "Rajesh Pandey" 
    - "Pandey R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Christine C Pazandak" 
  other_names: 
    - "Christine C Pazandak" 
    - "Pazandak CC" 
    - "Christine Pazandak" 
    - "Pazandak C" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Arun Prasath" 
  other_names: 
    - "Arun Prasath" 
    - "Prasath A" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Shalini Ramachandran" 
  other_names: 
    - "Shalini Ramachandran" 
    - "Ramachandran S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Tavleen Sandhu" 
  other_names: 
    - "Tavleen Sandhu" 
    - "Sandhu T" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Marina S Oren" 
  other_names: 
    - "Marina S Oren" 
    - "Oren MS" 
    - "Marina Oren" 
    - "Oren M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Lisa M Scheid" 
  other_names: 
    - "Lisa M Scheid" 
    - "Scheid LM" 
    - "Lisa Scheid" 
    - "Scheid L" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Julide Sisman" 
  other_names: 
    - "Julide Sisman" 
    - "Sisman J" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Katherine A Stumpf" 
  other_names: 
    - "Katherine A Stumpf" 
    - "Stumpf KA" 
    - "Katherine Stumpf" 
    - "Stumpf K" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "LaKeitha F Truehill" 
  other_names: 
    - "LaKeitha F Truehill" 
    - "Truehill LF" 
    - "LaKeitha Truehill" 
    - "Truehill L" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Sushmita Yallapragada" 
  other_names: 
    - "Sushmita Yallapragada" 
    - "Yallapragada S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Chelse� Johnson" 
  other_names: 
    - "Chelse� Johnson" 
    - "Johnson C" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Mohan Krishnan" 
  other_names: 
    - "Mohan Krishnan" 
    - "Krishnan M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Srinivas Kota" 
  other_names: 
    - "Srinivas Kota" 
    - "Kota S" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Balamurugan Ramatchandirin" 
  other_names: 
    - "Balamurugan Ramatchandirin" 
    - "Ramatchandirin B" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Myra H Wyckoff" 
  other_names: 
    - "Myra H Wyckoff" 
    - "Wyckoff MH" 
    - "Myra Wyckoff" 
    - "Wyckoff M" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Eric B Ortigoza" 
  other_names: 
    - "Eric B Ortigoza" 
    - "Ortigoza EB" 
    - "Eric Ortigoza" 
    - "Ortigoza E" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Vishal S Kapadia" 
  other_names: 
    - "Vishal S Kapadia" 
    - "Kapadia VS" 
    - "Vishal Kapadia" 
    - "Kapadia V" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Rachel L Leon" 
  other_names: 
    - "Rachel L Leon" 
    - "Leon RL" 
    - "Rachel Leon" 
    - "Leon R" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Venkatakrishna Kakkilaya" 
  other_names: 
    - "Venkatakrishna Kakkilaya" 
    - "Kakkilaya V" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

- full_name: "Abhishek Makkar" 
  other_names: 
    - "Abhishek Makkar" 
    - "Makkar A" 
  affiliations: 
    - "UT Southwestern" 
    - "UTSW" 
    - "University of Texas Southwestern" 
    - "University of Texas Southwestern Medical Center" 

